[package]
name = "dobby-subagent-code-summarizer"
version = "0.1.0"
edition = "2021"
description = "Real ONNX LLM inference for Tokio code summarization"

[dependencies]
# ONNX Runtime for ML inference
ort = { version = "2.0.0-rc.4", features = ["download-binaries", "copy-dylibs"] }
ndarray = "0.15"

# Async runtime
tokio = { version = "1.35", features = ["full"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging (optional for now)
# tracing = "0.1"
# tracing-subscriber = "0.3"

# Tokenization
tokenizers = "0.15"

# System metrics
sysinfo = "0.30"

# CLI argument parsing
clap = { version = "4.4", features = ["derive"] }

# Date/time for file naming
chrono = "0.4"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

# Binaries commented out for now - focus on library and tests
# [[bin]]
# name = "main"
# path = "main.rs"

# [[bin]]
# name = "simple_summarizer"
# path = "simple_summarizer.rs"

[[bin]]
name = "demo_summarize_tokio"
path = "src/bin/demo_summarize_tokio.rs"

[[bin]]
name = "code_summarizer"
path = "src/bin/code_summarizer.rs"

# [[bench]]
# name = "parallel_processing"
# harness = false

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
debug = true
overflow-checks = true