[package]
name = "deconstructor-core"
version = "0.1.0"
edition = "2024"

[dependencies]
linfa = "0.8.0"
linfa-clustering = "0.8.0"
md5 = { version = "0.8.0", optional = true }
ndarray = "0.16.1"

[dev-dependencies]
md5 = "0.8.0"

[features]
md5 = ["dep:md5"]
