version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: research_db
      POSTGRES_USER: research_user
      POSTGRES_PASSWORD: research_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U research_user -d research_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  research_app:
    build: .
    environment:
      DATABASE_URL: postgresql://research_user:research_pass@postgres:5432/research_db
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      RUST_LOG: info
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data

volumes:
  postgres_data: